# Generated by Django 4.1.2 on 2022-12-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='cathegory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='static/img/adopta.jpg', null=True, upload_to='media/images_news/'),
        ),
    ]
