# Generated by Django 4.1.3 on 2022-12-16 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='direccion',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='fecha_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='telefono',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='texto_denuncia',
            field=models.TextField(default='vacio', max_length=200),
        ),
    ]
