# Generated by Django 4.1.3 on 2022-12-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_denuncia_direccion_denuncia_email_denuncia_fecha_pub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='texto_denuncia',
            field=models.TextField(default='vacio', max_length=300),
        ),
    ]
