# Generated by Django 4.1.3 on 2022-12-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_denuncia_texto_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='telefono',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
